INSERT INTO TRUSTEE_TO_ANIMAL(USER_ID, ANIMAL_ID, DATE_CREATION) VALUES(1,3, CURRENT_TIMESTAMP);
INSERT INTO TRUSTEE_TO_ANIMAL(USER_ID, ANIMAL_ID, DATE_CREATION) VALUES(3,3, CURRENT_TIMESTAMP);
INSERT INTO TRUSTEE_TO_ANIMAL(USER_ID, ANIMAL_ID, DATE_CREATION) VALUES(2,5, CURRENT_TIMESTAMP);
